CREATE TABLE `packages` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `order_number` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `user_id` bigint NOT NULL,
  `bill_id` bigint DEFAULT NULL,
  `shipping_fee` decimal(11,2) DEFAULT '0.00',
  `label` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `recipient` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `company` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `phone_number` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `address_1` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `address_2` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `city` varchar(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `state_code` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `zipcode` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `country_code` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `detail` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `weight` decimal(11,2) DEFAULT NULL,
  `length` decimal(11,2) DEFAULT NULL,
  `width` decimal(11,2) DEFAULT NULL,
  `height` decimal(11,2) DEFAULT NULL,
  `status` int NOT NULL,
  `service_id` bigint DEFAULT NULL,
  `container_id` bigint DEFAULT NULL,
  `note` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `package_code_id` bigint DEFAULT NULL,
  `tracking_time` timestamp NULL DEFAULT NULL,
  `validate_address` tinyint DEFAULT '0',
  `checkin_warehouse_at` timestamp NULL DEFAULT NULL,
  `delivered_at` timestamp NULL DEFAULT NULL,
  `actual_weight` decimal(11,2) DEFAULT NULL,
  `actual_length` decimal(11,2) DEFAULT NULL,
  `actual_width` decimal(11,2) DEFAULT NULL,
  `actual_height` decimal(11,2) DEFAULT NULL,
  `checkin_request_id` bigint DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `alert` int DEFAULT NULL,
  `hub_exported_at` timestamp NULL DEFAULT NULL,
  `hub_imported_at` timestamp NULL DEFAULT NULL,
  `warehouse_id` bigint DEFAULT NULL,
  `user_id_imported` bigint DEFAULT NULL,
  `hub_id` bigint DEFAULT NULL,
  `returned_at` timestamp NULL DEFAULT NULL,
  `reship_at` timestamp NULL DEFAULT NULL,
  `request_reship` tinyint(1) DEFAULT '0',
  `label_promotion` tinyint(1) DEFAULT '0',
  `alert_at` timestamp NULL DEFAULT NULL,
  `is_package_exceed` int DEFAULT NULL,
  `order_id` bigint DEFAULT NULL,
  `customer_shipment_id` bigint DEFAULT NULL,
  `include_battery` tinyint(1) DEFAULT NULL,
  `is_insured` tinyint(1) DEFAULT '0',
  `is_bookmark` tinyint(1) DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_id` (`id`) USING BTREE,
  KEY `packages_users_id_fk` (`user_id`) USING BTREE,
  KEY `packages_bills_id_fk` (`bill_id`) USING BTREE,
  KEY `package_checkin_request_id_fk` (`checkin_request_id`) USING BTREE,
  KEY `package_code_idx` (`package_code_id`) USING BTREE,
  KEY `package_order_number_idx` (`order_number`) USING BTREE,
  KEY `packages_customer_shipment_id_IDX` (`customer_shipment_id`) USING BTREE,
  KEY `packages_service_id_fk` (`service_id`) USING BTREE,
  KEY `packages_order_idfk` (`order_id`) USING BTREE,
  UNIQUE(`order_number`, `user_id`),
  CONSTRAINT `packages_bills_id_fk` FOREIGN KEY (`bill_id`) REFERENCES `bills` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `packages_cshipment_idfk` FOREIGN KEY (`customer_shipment_id`) REFERENCES `customer_shipments` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `packages_order_idfk` FOREIGN KEY (`order_id`) REFERENCES `orders` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `packages_service_id_fk` FOREIGN KEY (`service_id`) REFERENCES `services` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `packages_users_id_fk` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT
);