CREATE TABLE `trackings` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `package_id` bigint DEFAULT NULL,
  `tracking_number` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `label_url` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `carrier_id` bigint DEFAULT NULL,
  `status` int DEFAULT NULL,
  `weight` decimal(11,2) DEFAULT NULL,
  `length` decimal(11,2) DEFAULT NULL,
  `width` decimal(11,2) DEFAULT NULL,
  `height` decimal(11,2) DEFAULT NULL,
  `shipment_cost` decimal(11,2) DEFAULT NULL,
  `user_id` bigint DEFAULT NULL,
  `hub_id` bigint DEFAULT NULL,
  `handling_fee` decimal(11,2) DEFAULT NULL,
  `carrier_service` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `zone` int DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `version` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `shipment_id` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `is_manifested` int DEFAULT '0',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_id` (`id`) USING BTREE,
  KEY `package_id` (`package_id`) USING BTREE,
  KEY `trackings_FK` (`hub_id`) USING BTREE,
  FULLTEXT KEY `tracking_number_idx` (`tracking_number`),
  CONSTRAINT `trackings_FK` FOREIGN KEY (`hub_id`) REFERENCES `warehouses` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `trackings_ibfk_1` FOREIGN KEY (`package_id`) REFERENCES `packages` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT
);