CREATE TABLE `shipments` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `price` decimal(11,2) NOT NULL DEFAULT '0.00',
  `status` int NOT NULL DEFAULT '0',
  `quantity` int DEFAULT NULL,
  `user_id` bigint DEFAULT NULL,
  `hub_id` bigint DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `close_at` timestamp NULL DEFAULT NULL,
  `warehouse_id` bigint DEFAULT NULL,
  `is_fba` tinyint DEFAULT NULL,
  `recipient` varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `address` varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `city` varchar(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `state` varchar(3) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `zipcode` varchar(20) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `country` varchar(3) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE,
  KEY `shipments_id_index` (`id`) USING BTREE,
  KEY `user_id` (`user_id`) USING BTREE,
  KEY `shipments_warehousevn_id_fk` (`warehouse_id`) USING BTREE,
  KEY `shipments_hub_id_fk` (`hub_id`) USING BTREE,
  CONSTRAINT `shipments_hub_id_fk` FOREIGN KEY (`hub_id`) REFERENCES `warehouses` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `shipments_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `shipments_warehousevn_id_fk` FOREIGN KEY (`warehouse_id`) REFERENCES `warehouses` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT
);