CREATE TABLE `containers` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `code` varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `tracking_number` varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `label_url` varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `carrier_id` bigint DEFAULT NULL,
  `length` decimal(11,2) DEFAULT NULL,
  `width` decimal(11,2) DEFAULT NULL,
  `height` decimal(11,2) DEFAULT NULL,
  `weight` decimal(11,2) NOT NULL DEFAULT '0.00',
  `actual_weight` decimal(11,2) DEFAULT '0.00',
  `max_weight` decimal(11,2) DEFAULT NULL,
  `status` int NOT NULL DEFAULT '0',
  `barcode` varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `shipment_id` bigint DEFAULT NULL,
  `hub_id` bigint DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `close_at` timestamp NULL DEFAULT NULL,
  `hub_exported_at` timestamp NULL DEFAULT NULL,
  `warehouse_id` bigint DEFAULT NULL,
  `hub_imported_at` timestamp NULL DEFAULT NULL,
  `type` int NOT NULL DEFAULT '1',
  `is_fba` tinyint DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE,
  KEY `shipment_id` (`shipment_id`) USING BTREE,
  KEY `containers_hub_id_fk` (`hub_id`) USING BTREE,
  KEY `containers_wid_fk` (`warehouse_id`) USING BTREE,
  CONSTRAINT `containers_ibfk_1` FOREIGN KEY (`shipment_id`) REFERENCES `shipments` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `containers_wid_fk` FOREIGN KEY (`warehouse_id`) REFERENCES `warehouses` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT
);