env="development"
tracking_env="development"
warehouse_vn_default=2

[fee]
returned=8

[mysql]
host = "127.0.0.1"
port = 3308
protocol = "tcp"
username = "tebexpress"
password = "tebexpress"
database = "tebexpress_dev"
charset = "utf8"
parse_time = true
debug=true

[redis]
addr="127.0.0.1:6379"
password="pass"
db=5

[api]
port=13602

[auth]
token_password="bxcrefagfr23"
token_expired_time= 2592000

[provider.ibblue]
base_url="https://api-sandbox.myibservices.com/"
api_key="nhantt@lionnix.vn:Lionnix1234@!"
weight_unit="g"
dimensions_unit="in"
image_format="png"
image_resolution=300
company_name="Lionnix LLC"
phone="1234567890"
address_line1="1625 Radcliff ave"
city_locality="Bronx"
state_province="NY"
postal_code="10462-4014"
country_code="US"
shape="Parcel"
mail_class="FirstClass"
mail_class_priority="Priority"
mail_class_parcel="ParcelSelect"
image_size="4x6"
gde_origin_country_code="VN"

[provider.darius]
base_url="http://119.91.146.95:8082"
label_url="http://119.91.146.95:8089"
username="PGL-024"
password="123456"
eu_shipper_name="ananbay"
eu_shipper_address="99/16 Nguyen Thai Binh Street, Quarter 04, Tan Binh District"
eu_shipper_postcode="100000"
eu_shipper_city="Ho Chi Minh"
eu_shipper_country="Vietnam"
eu_shipper_phone="84941869339"

[provider.yun]
base_url="http://oms.api.yunexpress.com"
username="CNV3504475"
password="27c5986b77a2412ebcd6fdf976e3925c"
mail_class="VNTHZXR"
company_name="Ananbay LLC"
city_locality="PORTLAND"
address_line1="11735 Southeast Yamhill Street"
state_province="OR"
postal_code="97216"
country_code="US"

[fedex]
base_url="https://apis-sandbox.fedex.com"
client_id="l703934d14224c40189099f7a5d9719468"
client_secret="2cc6e24b17df4755956b5af1a7d2b842"
auth_grant_type="client_credentials"
service_type="FEDEX_INTERNATIONAL_PRIORITY"
packaging_type="YOUR_PACKAGING"
pickup_type="USE_SCHEDULED_PICKUP"
account_number="740561073"
payment_type="SENDER"
description= "A/C Parts is an incomplete description and not accepted by Customs. An example of an acceptable description is Brake Caliper for Aircraft. Clearance delays may result if the contents are not completely and accurately described."
[fedex.address]
street_line="217 NGUYEN XIEN"
state_code="VN"
postal_code="100000"
city="HANOI"
country_code="VN"
[fedex.contact]
phone_number="0853312042"
name="Kien MrKien"
company_name="PHOENIX MANUFACTURE TRADING"

[b2]
ACCESS_KEY_ID = "0040d6b625417b80000000001"
SECRET_ACCESS_KEY = "K004K2aPS27xatT5OAgV5dL4F7obEbk"
DOMAIN = "s3.us-west-004.backblazeb2.com"

[aws]
S3_DOMAIN = "onuspro-np-nd-bucket"
S3_REGION = "ap-southeast-1"

[bucket]
packages = "ananbay-label-bucket"
labels = "ananbay-label-bucket"
shipping_packages = "ananbay-label-bucket"
export_billing = "ananbay-label-bucket"
thumbnails = "ananbay-label-bucket"
export_packages = "ananbay-label-bucket"

[package_refund]
day_expire_pending=1

[extra_fees]
reship_fee=1

[alert]
type="tele"
[alert.tele]
token="7392358940:AAGxjRhGhYyXaOME2OrrXWN1GvNinJi2W5c"
chat_id=-1002248220724