version: '3.3'
services:
  redis:
    image: redis:7.0.0-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass pass
    volumes:
      - "redis:/data"
    networks:
      - tebexpress
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # main RabbitMQ port
      - "15672:15672" # management UI
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: secret
volumes:
  redis:

networks:
  tebexpress:
    driver: bridge