package ups

const Additional_Handling = "100"
const Large_Package = "377"
const Ship_Additional_Handling = "401"
const Ship_Large_Package = "440"

var AccessorialOrSurchargeCodes = map[string]string{
	"100": "Additional handling",
	"110": "Cod",
	"120": "Delivery confirmation",
	"121": "Ship delivery confirmation",
	"190": "Extended area",
	"199": "Haz mat",
	"200": "Dry ice",
	"201": "Isc seeds",
	"202": "Isc perishables",
	"203": "Isc tobacco",
	"204": "Isc plants",
	"205": "Isc alcoholic beverages",
	"206": "Isc biological substances",
	"207": "Isc special exceptions",
	"220": "Hold for pickup",
	"240": "Origin certificate",
	"250": "Print return label",
	"258": "Export license verification",
	"260": "Print n mail",
	"270": "Residential address",
	"280": "Return service 1attempt",
	"290": "Return service 3attempt",
	"300": "Saturday delivery",
	"310": "Saturday international processing fee",
	"350": "Electronic return label",
	"374": "Ups prepared sed form",
	"375": "Fuel surcharge",
	"376": "Delivery area",
	"377": "Large package",
	"378": "Shipper pays duty tax",
	"379": "Shipper pays duty tax unpaid",
	"380": "Express plus surcharge",
	"400": "Insurance",
	"401": "Ship additional handling",
	"402": "Shipper release",
	"403": "Check to shipper",
	"405": "German pickup",
	"406": "German road tax",
	"407": "Extended area pickup",
	"410": "Return of document",
	"430": "Peak/demand season",
	"431": "Large package seasonal surcharge",
	"432": "Additional handling seasonal surcharge",
	"440": "Ship large package",
	"441": "Carbon neutral",
	"444": "Import control",
	"445": "Commercial invoice removal",
	"446": "Import control electronic label",
	"447": "Import control print label",
	"448": "Import control print and mail label",
	"449": "Import control one pick up attempt label",
	"450": "Import control three pick up attempt label",
	"452": "Refrigeration",
	"464": "Exchange print return label",
	"470": "Committed delivery window",
	"480": "Security surcharge",
	"492": "Customer transaction fee",
	"500": "Shipment cod",
	"510": "Lift gate for pickup",
	"511": "Lift gate for delivery",
	"512": "Drop off at ups facility",
	"515": "Ups premium care",
	"520": "Oversize pallet",
	"530": "Freight delivery surcharge",
	"531": "Freight pickup surcharge",
	"540": "Direct to retail",
	"541": "Direct delivery only/no access point",
	"542": "Deliver to addressee only",
	"543": "Direct to retail cod",
	"544": "Retail access point",
	"546": "Electronic package release authentication",
	"547": "Pay at store",
	"549": "Inside delivery",
	"550": "Item disposal",
	"551": "Uk border fee",
	"555": "Ups premier silver",
	"556": "Ups premier gold",
	"557": "Ups premier platinum",
	"558": "Ddu oversize",
}
