package constant

const (
	NOTIFY_TYPE_ORDER_UPDATE   = 1
	NOTIFY_TYPE_FINANCE_UPDATE = 2
	NOTIFY_TYPE_ANNOUNCEMENT   = 3
	NOTIFY_TYPE_SERVICE_UPDATE = 4
	NOTIFY_TYPE_PROMOTION      = 5
	NOTIFY_TYPE_EXPORT_FILE = 6
)

var NotifyTypes = []int64{
	NOTIFY_TYPE_ORDER_UPDATE,
	NOTIFY_TYPE_FINANCE_UPDATE,
	NOTIFY_TYPE_ANNOUNCEMENT,
	NOTIFY_TYPE_SERVICE_UPDATE,
	NOTIFY_TYPE_PROMOTION,
}
