package auspost

import (
	"encoding/json"
	"fmt"
	"tebexpressapi/pkg/utils"
	"time"
)

type ShipmentRequest struct {
	// A unique reference for the shipment, generated by the merchant.	Optional	String	50
	ShipmentReference string `json:"shipment_reference,omitempty"`

	// A merchant specified array of references for the shipment.
	// Effectively deprecates customer_reference_1 and customer_reference_2.
	// The array length supported varies as noted in the Sender references documentation.	Optional	Array
	SenderReferences []string `json:"sender_references,omitempty"`

	// A merchant specified reference for the shipment.
	// This value is not required to be unique.	Optional	String	50
	CustomerReference1 string `json:"customer_reference_1,omitempty"`

	// A merchant specified reference for the shipment.
	// This value is not required to be unique.	Optional	String	50
	CustomerReference2 string `json:"customer_reference_2,omitempty"`

	// Description of the goods. This is printed on the auxiliary label.
	// A maximum of 3 lines, each with a maximum of 40 characters.	Optional	Array	40
	GoodsDescriptions []string `json:"goods_descriptions,omitempty"`

	// Despatch Date of a shipment. Date should be supplied in the following format yyyy-MM-dd.
	// Note - Despatch Date cannot be more than 14 days in future, and cannot be in the past.	Optional	String
	DespatchDate string `json:"despatch_date,omitempty"`

	// If set true, the system attempts to search for existing
	// pending shipments to consolidate this shipment with.
	// If set to false, a new shipment is created as per normal workflow.
	// Note that the consolidate field is only available for StarTrack products.
	// For further information on consolidation, please refer to Shipment Consolidation.
	// Optional - if unassigned, defaults to true for StarTrack products, otherwise defaults to false
	// Boolean - true or false	N/A
	Consolidate bool `json:"consolidate,omitempty"`

	// Whether the recipient of the shipment will receive tracking notification email.
	// The email address of the receiver must be provided if the email_tracking_enabled field is set to true.
	// Optional - for some products this defaults to true	Boolean - true or false	N/A
	EmailTrackingEnabled bool `json:"email_tracking_enabled,omitempty"`

	// If set to True, the metadata for the label will be returned with the shipment,
	//  for the merchant to incorporate into their own label.
	// For detailed information please refer to Generate Label Metadata.	Optional	String	N/A
	GenerateLabelMetadata string `json:"generate_label_metadata,omitempty"`

	// The address where the items will be sent from.
	From Address `json:"from"`

	// The address where the items will be delivered.
	To Address `json:"to"`

	// Use "DESPATCH" to indicate an outbound or normal shipment (this is the default),
	// "RETURN" to indicate a returns shipment,
	// "TRANSFER" to indicate a transfer.
	// "TRANSFER" is only available for StarTrack products.	Optional	String	8
	MovementType string `json:"movement_type,omitempty"`

	// Additional features for the shipment.	Optional
	Features map[string]Attributes `json:"features,omitempty"`

	// The merchant's internal reference ID for a returns or transfer shipment.
	// This is mandatory for StarTrack if movement_type is "RETURN" and "TRANSFER".	Optional (See Desc.)	String	10
	AuthorisationNumber string `json:"authorisation_number,omitempty"`

	Items []Item `json:"items"`
}

type Item struct {
	// A unique reference for the item, generated by the merchant.	Optional	String	50
	ItemReference string `json:"item_reference,omitempty"`

	// The Australia Post code representing the postage product for the item.	Mandatory	String	5
	ProductID string `json:"product_id"`

	// A description of the item, generated by the merchant.	Optional	String
	ItemDescription string `json:"item_description,omitempty"`

	// The length of the parcel in centimetres.
	// If volumetric pricing applies then this is mandatory.
	// Alternatively, you can use the cubic_volume field.
	// You cannot specify both length/width/height and cubic_volume.
	// Optional (See Desc.)	Decimal	4.1
	Length float64 `json:"length"`

	// The width of the parcel in centimetres.
	// If volumetric pricing applies then this is mandatory.
	// Please refer to the length field for more information.
	// Optional (See Desc.)	Decimal	4.1
	Width float64 `json:"width"`

	// The height of the parcel in centimetres.
	// If volumetric pricing applies then this is mandatory.
	// Please refer to the length field for more information.
	// Optional (See Desc.)	Decimal	4.1
	Height float64 `json:"height"`

	// The volume of the item in cubic metres.
	// If volumetric pricing applies, then volume is mandatory.
	// To specify volume, you can use the cubic_volume field
	// or the length/width/height fields, but not both.
	// Note that the cubic_volume field is only available
	// for StarTrack products and New Zealand Commercial products.
	// Optional (See Desc.)	Decimal	5.7
	CubicVolume *float64 `json:"cubic_volume,omitempty"`

	// The parcel’s weight in kilograms.
	// This must not be specified for flat-rate return shipments (movement_type = RETURN).
	// However, it is mandatory for normal (outbound) shipments (movement_type = DESPATCH)
	// and zonal returns (movement_type = RETURN).
	// Your contract with Australia Post (not your API call)
	// determines whether a return shipment has zonal pricing or flat-rate pricing.
	// Note that most returns contracts are flat-rate.	See Desc.	Decimal	N.3
	Weight float64 `json:"weight"`

	// Whether the item contains dangerous goods, generated by the merchant.
	// Optional. Defaults to false.	Boolean - true or false
	ContainsDangerousGoods *bool `json:"contains_dangerous_goods,omitempty"`

	// If the goods being sent are dangerous but are permitted to be transported by air,
	// set this value to 'true'.	(Optional)	Boolean - true or false
	TransportableByAir *bool `json:"transportable_by_air,omitempty"`

	// If the goods being sent are dangerous and the transportable_by_air value is 'true',
	// then the DG Declaration becomes mandatory.
	// The DG declaration value can be found here.	See Desc.	String
	DangerousGoodsDeclaration *string `json:"dangerous_goods_declaration,omitempty"`

	// Whether the item can be left in a safe place on delivery without receiving a signature.
	// This is optional for domestic shipments (and defaults to true),
	// but must not be specified for international shipments.	See Desc.	Boolean - true or false
	AuthorityToLeave *bool `json:"authority_to_leave,omitempty"`

	// Whether your customer can request that the item be left in
	// a safe place at the delivery address if they are not home to sign for their delivery.
	// Your customer can request this while the item is on its way.
	// This field is optional for domestic shipments (and defaults to true),
	// but must not be specified for international shipments.
	// This field works with the authority_to_leave field.
	// If the authority_to_leave field is set to true, the safe_drop_enabled field is ignored.
	// Please review the fact sheet for full details.	See Desc.	Boolean - true or false
	SafeDropEnabled *bool `json:"safe_drop_enabled,omitempty"`

	// Whether items can be delivered to their final destination
	// as they become available or whether all items in the resulting
	// consignment must be delivered together.
	// Optional. Defaults to true.	Boolean - true or false	N/A
	AllowPartialDelivery *bool `json:"allow_partial_delivery,omitempty"`

	// The packaging type for this item. Some example values are: CTN, PAL, SAT, BAG, ENV, ITM, JIF, SKI
	// Note, for StarTrack products, the packaging type (refereed to as a unit type by StarTrack)
	// is mandatory and has a maximum length of 3.	Mandatory for StarTrack, otherwise Optional	String	3
	PackagingType *string `json:"packaging_type,omitempty"`

	// Authority to Leave (ATL) authorisation code.
	// If this field is provided, it must begin with C and be followed by a 9 digit number.	Optional	String	10
	AtlNumber *string `json:"atl_number,omitempty"`

	// Additional features for the item.	Optional
	Features *map[string]Attributes `json:"features,omitempty"`

	// The merchant can optionally define the specific consignment, article,
	// and barcode identifiers for the item. If this information is not supplied,
	// Australia Post will generate the identifiers. Important note:
	// if you are generating your own identifiers you must adhere to the
	// specifications provided by Australia Post. Please contact Lodgement and APIs support for details.	Optional
	TrackingDetails *TrackingDetail `json:"tracking_details,omitempty"`
}

type FormCreateShipment struct {
	Shipments []ShipmentRequest `json:"shipments"`
}

type ShipmentResponse struct {
	ShipmentID           string    `json:"shipment_id"`
	ShipmentReference    string    `json:"shipment_reference,omitempty"`
	CustomerReference1   string    `json:"customer_reference_1,omitempty"`
	CustomerReference2   string    `json:"customer_reference_2,omitempty"`
	SenderReferences     []string  `json:"sender_references,omitempty"`
	ShipmentCreationDate time.Time `json:"shipment_creation_date"`
	ShipmentModifiedDate time.Time `json:"shipment_modified_date"`
	EmailTrackingEnabled bool      `json:"email_tracking_enabled,omitempty"`

	Items []struct {
		ItemID          string  `json:"item_id"`
		ProductID       string  `json:"product_id"`
		ItemReference   string  `json:"item_reference"`
		ItemDescription string  `json:"item_description"`
		Length          float64 `json:"length"`
		Width           float64 `json:"width"`
		Height          float64 `json:"height"`
		CubicVolume     float64 `json:"cubic_volume"`
		Weight          float64 `json:"weight"`

		TrackingDetails struct {
			ArticleID     string `json:"article_id"`
			ConsignmentID string `json:"consignment_id"`
		} `json:"tracking_details"`

		ItemSummary struct {
			TotalCost               float64 `json:"total_cost"`
			TotalCostExGst          float64 `json:"total_cost_ex_gst"`
			TotalGst                float64 `json:"total_gst"`
			ManualHandlingSurcharge float64 `json:"manual_handling_surcharge"`
			Status                  float64 `json:"status"`
		} `json:"item_summary"`
	} `json:"items"`

	ShipmentSummary struct {
		TotalCost               float64        `json:"total_cost"`
		TotalCostExGst          float64        `json:"total_cost_ex_gst"`
		FuelSurcharge           float64        `json:"fuel_surcharge"`
		TotalGst                float64        `json:"total_gst"`
		ManualHandlingSurcharge float64        `json:"manual_handling_surcharge"`
		NumberOfItems           int64          `json:"number_of_items"`
		Status                  float64        `json:"status"`
		TrackingSummary         map[string]int `json:"tracking_summary"`
	} `json:"shipment_summary"`
}

type CreateShipmentResponse struct {
	Shipments []struct {
		ShipmentID           string    `json:"shipment_id"`
		ShipmentReference    string    `json:"shipment_reference"`
		ShipmentCreationDate time.Time `json:"shipment_creation_date"`
		EmailTrackingEnabled bool      `json:"email_tracking_enabled"`

		Items []struct {
			Weight                 float64     `json:"weight"`
			ContainsDangerousGoods bool        `json:"contains_dangerous_goods"`
			AuthorityToLeave       bool        `json:"authority_to_leave"`
			SafeDropEnabled        bool        `json:"safe_drop_enabled"`
			AllowPartialDelivery   bool        `json:"allow_partial_delivery"`
			ItemID                 string      `json:"item_id"`
			ItemReference          string      `json:"item_reference"`
			ProductID              string      `json:"product_id"`
			ItemContents           interface{} `json:"item_contents"`

			TrackingDetails struct {
				ArticleID     string `json:"article_id"`
				ConsignmentID string `json:"consignment_id"`
			} `json:"tracking_details"`

			ItemSummary struct {
				TotalCost      float64 `json:"total_cost"`
				TotalCostExGst float64 `json:"total_cost_ex_gst"`
				TotalGst       float64 `json:"total_gst"`
				Status         string  `json:"status"`
			} `json:"item_summary"`
		} `json:"items"`

		ShipmentSummary struct {
			TotalCost       float64        `json:"total_cost"`
			TotalCostExGst  float64        `json:"total_cost_ex_gst"`
			ShippingCost    float64        `json:"shipping_cost"`
			FuelSurcharge   float64        `json:"fuel_surcharge"`
			TotalGst        float64        `json:"total_gst"`
			Status          string         `json:"status"`
			NumberOfItems   int            `json:"number_of_items"`
			TrackingSummary map[string]int `json:"tracking_summary"`
		} `json:"shipment_summary"`

		Options              interface{} `json:"options"`
		MovementType         string      `json:"movement_type"`
		ChargeToAccount      string      `json:"charge_to_account"`
		ShipmentModifiedDate time.Time   `json:"shipment_modified_date"`
	} `json:"shipments"`
}

func (au *Auspost) CreateShipment(in LabelRequest) (*CreateShipmentResponse, *ResponseErrors, error) {
	to := Address{
		Name:         in.FullName,
		Lines:        []string{in.Address1},
		Suburb:       in.City,
		State:        in.State,
		Postcode:     in.Zipcode,
		Phone:        in.Phone,
		Email:        in.Email,
		Country:      in.Country,
		BusinessName: in.Company,
	}

	if in.Address2 != "" {
		to.Lines = append(to.Lines, in.Address2)
	}

	from := au.Address
	if in.WarehouseAddress1 != "" {
		from = Address{
			Name:     in.WarehouseCompany,
			Lines:    []string{in.WarehouseAddress1},
			Suburb:   in.WarehouseCity,
			State:    in.WarehouseState,
			Postcode: in.WarehouseZipcode,
			Phone:    in.WarehousePhone,
			Country:  in.WarehouseCountry,
		}
	}

	var emailTrackingEnabled bool
	if in.Email != "" {
		emailTrackingEnabled = true
	}

	references := []string{}
	if in.OrderNumber != "" {
		references = append(references, in.OrderNumber)
	}

	if in.Code != "" {
		references = append(references, in.Code)
	}

	payload := FormCreateShipment{
		Shipments: []ShipmentRequest{
			{
				ShipmentReference:    fmt.Sprintf("%v-%v", in.PackageID, time.Now().Unix()),
				SenderReferences:     references,
				EmailTrackingEnabled: emailTrackingEnabled,
				From:                 from,
				To:                   to,
				Items: []Item{
					{
						ItemReference:        in.OrderNumber,
						ProductID:            au.ProductParcelPostID,
						Length:               in.Length,
						Height:               in.Height,
						Width:                in.Width,
						Weight:               in.Weight,
						AuthorityToLeave:     utils.Bool(true),
						AllowPartialDelivery: utils.Bool(true),
					},
				},
			},
		},
	}

	var response interface{}
	if err := au.Client.Post("/shipping/v1/shipments", payload, &response); err != nil {
		return nil, nil, err
	}

	b, err := json.Marshal(response)
	if err != nil {
		return nil, nil, err
	}

	result := &CreateShipmentResponse{}
	err = json.Unmarshal(b, result)
	if err != nil {
		return nil, nil, err
	}

	if len(result.Shipments) > 0 {
		return result, nil, nil
	}

	errors := &ResponseErrors{}
	err = json.Unmarshal(b, errors)
	if err != nil {
		return nil, nil, err
	}

	return nil, errors, nil
}
