package auspost

const (
	MaxWidth          = 105    // cm
	MaxHeight         = 105    // cm
	MaxLength         = 105    // cm
	MaxVolume         = 250000 // cm3
	MaxWeight         = 32     // kg
	MaxLengthAddress  = 40     // ký tự
	MaxLengthCity     = 40     // ký tự
	MaxLengthFullName = 40     // ký tự
	MaxLengthPostcode = 4      // ký tự
	MaxLengthState    = 3      // ký tự
)

type Options struct {
	Username             string
	Password             string
	AccountNumber        string
	BaseURL              string
	Address              Address
	ProductExpressID     string
	ProductParcelPostID  string
	ProductExpressName   string
	ProductExpressLayout string
	ISDevelopment        bool
}

type Estimate struct {
	Username      string
	Password      string
	AccountNumber int64
	BaseURL       string
}

type Address struct {
	// The name of the sender.	Mandatory	String	40
	Name string `json:"name"`

	// The Australia Post customer number.	Optional	String	10
	Apcn string `json:"apcn,omitempty"`

	// The name of the sending business.	Optional	String	40
	BusinessName string `json:"business_name,omitempty"`

	// The type of address. If this field is supplied,
	// its value must be "MERCHANT_LOCATION".	Optional	String (See Desc.)
	Type string `json:"type,omitempty"`

	// The address lines of the address.
	// Minimum of one address line,
	// up to a maximum of three for Australia Post products,
	// and up to a maximum of two for StarTrack products.
	// Each address line is a maximum of 40 characters.	Mandatory	Array	40
	Lines []string `json:"lines"`

	// The suburb for the address.	Mandatory	String	40
	Suburb string `json:"suburb"`

	// The state code for the address.
	// Valid values are: ACT, NSW, NT, QLD, SA, TAS, VIC, WA.	Mandatory	String	3
	State string `json:"state"`

	// The postcode for the address.	Mandatory	String	4
	Postcode string `json:"postcode"`

	// The country code for the address.	Optional. If specified, it must be "AU".	String	2
	Country string `json:"country"`

	// The sender's phone number. For StarTrack shipments,
	// the maximum length is 10 characters and the allowable
	// characters are "0-9" (digits only.) Examples are: 0491570156, 0855502312.
	// For AusPost shipments, the maximum length is 20 characters and
	// the allowable characters are "+()- 0-9" (plus, digits, space, hyphen and parentheses.)
	// Examples are: 0491-570-156, 02) 5550 1234, +61 (3) 7010 4321.	Optional	String	See Desc.
	Phone string `json:"phone,omitempty"`

	// The sender’s email address.	Optional	String	50
	Email string `json:"email,omitempty"`

	// Instructions to aid in prompt delivery of the item.
	// Note - For StarTrack products, delivery instructions
	// is an array of strings with a maximum of 3 lines,
	// each with a maximum of 25 characters.
	// Delivery instructions for StarTrack products will be printed
	// as "Special instructions" on labels.	Optional	String	128
	DeliveryInstructions string `json:"delivery_instructions,omitempty"`
}

type TrackingDetail struct {
	// The consignment ID, generated by the merchant, to be assigned to the item.	Mandatory	String	30
	ConsignmentID string `json:"consignment_id"`

	// The article ID, generated by the merchant, to be assigned to the item.	Mandatory	String	30
	ArticleID string `json:"article_id"`

	// The barcode ID, generated by the merchant, to be assigned to the item.	Mandatory	String
	BarcodeID string `json:"barcode_id"`
}

type Attributes struct {
	Attributes map[string]interface{} `json:"attributes"`
}

type ResponseError struct {
	Code    string `json:"code"`
	Name    string `json:"name"`
	Field   string `json:"field"`
	Message string `json:"message"`
}

type ResponseErrors struct {
	Errors []ResponseError `json:"errors"`
}
